### PR TITLE
Mw/envsetup

### PR DESCRIPTION
**Pull request by MartinWallgren**
Added scripts/envsetup

[Review on Reviewable](https://reviewable.io/reviews/amhk/lokatt/11)

### CODE REVIEW

**Comment by amhk** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/11)







---

<sup>**[scripts/envsetup.sh, line 23 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/11#-Jir3XbSZucVbiDHdLvZ)** ([raw file](https://github.com/amhk/lokatt/blob/3adcdaeac711b438cb30078f46a4735d8ce4cc4f/scripts/envsetup.sh#L23)):</sup>
If a previous command in a function fails, that won't be reflected by the final return $?.

---

<sup>**[scripts/envsetup.sh, line 37 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/11#-Jir3QXf2QAy1KI0evzv)** ([raw file](https://github.com/amhk/lokatt/blob/3adcdaeac711b438cb30078f46a4735d8ce4cc4f/scripts/envsetup.sh#L37)):</sup>
should deactivate be called here?

---

**Comment by MartinWallgren** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/11)







---

<sup>**[scripts/envsetup.sh, line 23 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/11#-Jir3XbSZucVbiDHdLvZ)** ([raw file](https://github.com/amhk/lokatt/blob/3adcdaeac711b438cb30078f46a4735d8ce4cc4f/scripts/envsetup.sh#L23)):</sup>
Did you place this comment on the correct line? There are no other executed commands in this function. Although it would make sense in the context of _lokatt_create_venv

Or am I missing something? 

---

**Comment by amhk** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/11)







---

<sup>**[scripts/envsetup.sh, line 23 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/11#-Jir3XbSZucVbiDHdLvZ)** ([raw file](https://github.com/amhk/lokatt/blob/3adcdaeac711b438cb30078f46a4735d8ce4cc4f/scripts/envsetup.sh#L23)):</sup>
Ehm, both yes and no. In this function it's fine since, as you point out, there's only one command. I was thinking of the other functions and just stuck this comment in the first place I found a `return $?`...

---

**Comment by MartinWallgren** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/11)







---

<sup>**[scripts/envsetup.sh, line 23 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/11#-Jir3XbSZucVbiDHdLvZ)** ([raw file](https://github.com/amhk/lokatt/blob/3adcdaeac711b438cb30078f46a4735d8ce4cc4f/scripts/envsetup.sh#L23)):</sup>
Got it

---

<sup>**[scripts/envsetup.sh, line 37 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/11#-Jir3QXf2QAy1KI0evzv)** ([raw file](https://github.com/amhk/lokatt/blob/3adcdaeac711b438cb30078f46a4735d8ce4cc4f/scripts/envsetup.sh#L37)):</sup>
Having the deactivate there will make the function behave as the original implementation ***{PYVENV} ${T}/venv. ({PYVENV} ${T}/venv will not activate the venv)
So we don't get any surprises once we revert the work around.

---

**Comment by amhk** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/11)

Reviewed files:
- .gitignore @ r1
- scripts/dependencies.txt @ r1
- scripts/envsetup.sh @ r1, r2





---

<sup>**[scripts/envsetup.sh, line 41 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/11#-Jir3QXf2QAy1KI0evzv)** ([raw file](https://github.com/amhk/lokatt/blob/3adcdaeac711b438cb30078f46a4735d8ce4cc4f/scripts/envsetup.sh#L41)):</sup>
Aha. Sounds good.

Also: stupid GUI to only show the "squashed" final version and not individual commits.

---

**Comment by MartinWallgren** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/11)



---

last patch set is just a rebase since you already added the scripts directory

---

**Comment by amhk** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/11)

Reviewed files:
- scripts/envsetup.sh @ r3

---

+2. Will merge this.

---

**Comment by amhk** [comment]
Branch merged manually.

**Pull request closed without merging**
