### PR TITLE
Channel api

### PR DESCRIPTION
**Pull request by MartinWallgren**
[Review on Reviewable](https://reviewable.io/reviews/amhk/lokatt/3)

### CODE REVIEW

**Comment by amhk** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/3)

Reviewed files:
- cli/cli.py @ r1
- common/lib/bridge.c @ r1
- common/lib/bridge.h @ r1
- common/lib/demux.c @ r1
- common/lib/lokatt.h @ r1
- common/lib/Makefile @ r1
- common/liblokatt.py @ r1

---

I'd like a test-bridge.c while we're at it, if feasible... is a test case worth the effort to create and maintain one?

https://reviewable.io seems pretty capable, but it's annoying how it (and github.com) won't show you individual commits, just the end result (as if all commits were squashed). Am I missing some magic button to limit what I see?

---

<sup>**[cli/cli.py, line 3 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIUi8BAxWqZ0zsVkKp)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/cli/cli.py#L3)):</sup>
Please remove this blank line.

---

<sup>**[cli/cli.py, line 51 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIV7ySaQcojfA6UE7w)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/cli/cli.py#L51)):</sup>
I prefer to have functions defined at the very start of the function in which they're defined, since this, to me, increases readability.

Your thoughts?

---

<sup>**[cli/cli.py, line 58 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIVZRPUmj6_SkDZnkO)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/cli/cli.py#L58)):</sup>
Won't key input be handled on the main thread?

---

<sup>**[cli/cli.py, line 62 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIW7zY9X9uZQYmGbPk)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/cli/cli.py#L62)):</sup>
Doesn't this commit replace part of the stuff in liblokatt.py? Why is the client required to both implement on_message *and* pass in a callback to logcat.create_channel?

Remove the on_message function from View? Maybe we should rethink the View API by removing it for now, toying around with the text based client for a few commits, and reintroduce View once we have more experience with implementing the cli?

---

<sup>**[common/lib/bridge.c, line 12 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIQ3waXo5aZwgprDWY)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.c#L12)):</sup>
Extraneous blank line. The horror!

---

<sup>**[common/lib/bridge.c, line 15 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIPvsmwsTgW8HnXw3U)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.c#L15)):</sup>
This and other functions not specified in bridge.h should be marked 'static'.

---

<sup>**[common/lib/bridge.c, line 18 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIQE7JE7zyhhZ0sUim)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.c#L18)):</sup>
No space between ) and variable name in casts, please.

---

<sup>**[common/lib/bridge.c, line 19 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIUFdljYlKzoZ-pQR9)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.c#L19)):</sup>
The line 

```
while (read_lokatt_channel(ac->c, &m) != -1)
```

is fine, but I see it's changed from the previous commit. Would it be possible to move this fixup to the previous commit so this one doesn't have to include it?

---

<sup>**[common/lib/bridge.c, line 20 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIQLMXMZFFgII0oL62)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.c#L20)):</sup>
No curly braces for one line statement blocks.

---

<sup>**[common/lib/bridge.c, line 44 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIQrI984Hcur8-13WL)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.c#L44)):</sup>
Align 'message_callback' with 'struct' on the previous line.

set cinoptions=:0,l1,t0,g0,(0

in vim, and reindent the line (==).

---

<sup>**[common/lib/bridge.c, line 50 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIRH4_ZpQCebxpCFDp)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.c#L50)):</sup>
For now, I'm OK with just calling die() (from error.h).

---

<sup>**[common/lib/bridge.h, line 6 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiINXSfnIqCHK7NnP6E)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.h#L6)):</sup>
Please change parameter to its const equivalent:

const struct lokatt_message *

---

<sup>**[common/lib/bridge.h, line 8 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIOMxwYdsnVZiSBAfI)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.h#L8)):</sup>
struct async_channel is "private" to bridge.c, which is just fine. Consider returning a void pointer, as an opaque handle, instead. This pointer may still be a pointer to async_channel, just don't tell the caller of open_new_channel that.

(I know this is not the pattern employed in adb.h for struct adb_stream, but *it should have been!*)

---

<sup>**[common/lib/bridge.h, line 12 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiINp1U5oHFLANczRlM)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.h#L12)):</sup>
Please add a space before #endif.

---

<sup>**[common/lib/demux.c, line 29 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIRzV2j9SRCwPmC82R)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/demux.c#L29)):</sup>
is_closed is just fine as a variable name. An alternative, that my be too cumbersome right now, but entices me nonetheless, is

enum {
STATE_CLOSED,
STATE_OPEN,
} state;

Your thoughts?

---

<sup>**[common/lib/demux.c, line 156 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIS_EWMcpJTVVAnSMx)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/demux.c#L156)):</sup>
I'd prefer struct lokatt_session *s be declared at the beginning of this function.

---

<sup>**[common/lib/demux.c, line 157 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiISgL5rOOHolbILNe5)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/demux.c#L157)):</sup>
Line too long (but the comment itself is appreciated).

Please use /* ... */ for comments in C.

---

<sup>**[common/lib/demux.c, line 180 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiITo51XNcuvHZublZY)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/demux.c#L180)):</sup>
This copy of this comment should be removed (it's actually moved further down).

---

<sup>**[common/lib/demux.c, line 183 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiITcdWR1Xev_zEaT9X)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/demux.c#L183)):</sup>
missing question mark in comment

---

<sup>**[common/lib/lokatt.h, line 42 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIRe_B33C8WRiKwEzO)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/lokatt.h#L42)):</sup>
I'd prefer 'is_lokatt_channel_closed' or something similar with lokatt_channel in the name. No namespaces -> need to explicitly spell out the "namespace" for each item, I'm afraid.

---

<sup>**[common/liblokatt.py, line 49 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIXyz4oVO0VtVTEOyK)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/liblokatt.py#L49)):</sup>
Rename to LogcatSession? Or LokattSession?

---

<sup>**[common/liblokatt.py, line 60 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIXF40w8ZBxMRIdLDB)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/liblokatt.py#L60)):</sup>
is_open is a more descriptive name?

Actually, doesn't PEP8 specify that "private" variables should begin with a leading underscore?

---

<sup>**[common/liblokatt.py, line 64 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIXcrW0rQ5MMwmqL5-)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/liblokatt.py#L64)):</sup>
Perhaps it's better to just raise an exception, like is done in stop? Your thoughts?

---

<sup>**[common/liblokatt.py, line 101 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIY_P-NQjTG7HhOFeD)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/liblokatt.py#L101)):</sup>
" ?

---

<sup>**[common/liblokatt.py, line 113 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIYjQLfBZwp2wzeoGv)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/liblokatt.py#L113)):</sup>
pass?

---

<sup>**[common/liblokatt.py, line 121 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIYe1RiSzbcOLkI2OU)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/liblokatt.py#L121)):</sup>
pass?

---

**Comment by MartinWallgren** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/3)







---

<sup>**[common/lib/bridge.c, line 18 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIQE7JE7zyhhZ0sUim)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.c#L18)):</sup>
I will never get used to this, prepare seeing this every time I cast something

---

**Comment by MartinWallgren** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/3)







---

<sup>**[common/lib/bridge.h, line 11 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiJ3T1Qld0FwZwubzCs)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.h#L11)):</sup>
Should I change the handle in close to void pointer as well?

---

**Comment by amhk** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/3)







---

<sup>**[common/lib/bridge.h, line 11 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiJ3T1Qld0FwZwubzCs)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.h#L11)):</sup>
Yes please. And in the implementation of close_async_channel, just cast the void * to the struct async_channel * it actually is.

---

**Comment by MartinWallgren** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/3)



---

Agreed, I'll add test-bridge.c.

---

<sup>**[cli/cli.py, line 51 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIV7ySaQcojfA6UE7w)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/cli/cli.py#L51)):</sup>
I usually declare things as close as possible to where it will be used, but either way is fine. 

---

<sup>**[cli/cli.py, line 58 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIVZRPUmj6_SkDZnkO)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/cli/cli.py#L58)):</sup>
Yes, but we need to stop the main thread from ending, since it will end the entire program. I'm just putting it to sleep at the moment, but we should probably do something else with it. That is what the comment is referring to.

---

<sup>**[cli/cli.py, line 62 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIW7zY9X9uZQYmGbPk)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/cli/cli.py#L62)):</sup>
on_message should never have been merged, it is from an early prototype. I have removed it in a local commit but it is not pushed. Since it is not part of this change I prefer to not correct it here.
I plan to deliver it together with some project cleaning where I intend to add virtualenv, testcases for python, scripts dir and add a Makefile in the root for starting common tasks (tests, autopep8 formatting and such).

Sound ok?

---

<sup>**[common/lib/bridge.c, line 18 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIQE7JE7zyhhZ0sUim)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.c#L18)):</sup>
Done.

---

<sup>**[common/lib/bridge.c, line 19 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIUFdljYlKzoZ-pQR9)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.c#L19)):</sup>
Yes, that was my intention, my rebase foo failed me. Will fix

---

<sup>**[common/lib/bridge.c, line 20 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIQLMXMZFFgII0oL62)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.c#L20)):</sup>
I'm cross checking your comments on code style with https://www.kernel.org/doc/Documentation/CodingStyle
I'll accept it, but note my disgruntled sigh.

---

<sup>**[common/lib/bridge.h, line 8 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIOMxwYdsnVZiSBAfI)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.h#L8)):</sup>
The same for struct lokatt_session and struct lokatt_channel in lokatt.h ;) 

---

<sup>**[common/lib/bridge.h, line 11 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiJ3T1Qld0FwZwubzCs)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.h#L11)):</sup>
Done.

---

<sup>**[common/lib/demux.c, line 29 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIRzV2j9SRCwPmC82R)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/demux.c#L29)):</sup>
Yes, enums are better. Could even use the same enum to keep the state in lokatt_session

---

<sup>**[common/liblokatt.py, line 49 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIXyz4oVO0VtVTEOyK)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/liblokatt.py#L49)):</sup>
Logcat was intentional since it is a representation of "adb logcat" (even though the implementation is a lokatt_session). I do agree that we should slap a Session on there to LogatSession

---

<sup>**[common/liblokatt.py, line 60 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIXF40w8ZBxMRIdLDB)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/liblokatt.py#L60)):</sup>
yes and yes

---

<sup>**[common/liblokatt.py, line 101 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIY_P-NQjTG7HhOFeD)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/liblokatt.py#L101)):</sup>
Just want to keep you on your toes

---

<sup>**[common/liblokatt.py, line 113 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIYjQLfBZwp2wzeoGv)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/liblokatt.py#L113)):</sup>
And not even correctly aligned to the open method. madness

---

**Comment by amhk** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/3)

Reviewed files:
- cli/cli.py @ r2
- common/lib/bridge.c @ r1, r2
- common/lib/bridge.h @ r2
- common/lib/demux.c @ r2
- common/lib/lokatt.h @ r2
- common/liblokatt.py @ r2





---

<sup>**[cli/cli.py, line 51 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIV7ySaQcojfA6UE7w)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/cli/cli.py#L51)):</sup>
Yeah, that makes sense too... I can't really decide on this one. Whichever approach works just fine.

---

<sup>**[cli/cli.py, line 58 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIVZRPUmj6_SkDZnkO)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/cli/cli.py#L58)):</sup>
Ah, right, I didn't get that. How about a pthread_cond_wait (or whatever the equivalent is in Python) for the main thread?

We can replace the poll/sleep pattern in a later commit if you don't want to mess any more with this upload. If we postpone it, please open a new issue on github so we can track the intended change.

---

<sup>**[cli/cli.py, line 62 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIW7zY9X9uZQYmGbPk)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/cli/cli.py#L62)):</sup>
Sounds great. Looking forward to it.

---

<sup>**[common/lib/bridge.c, line 19 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIQLMXMZFFgII0oL62)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.c#L19)):</sup>
Disgruntled sigh acknowledged. And ignored. ;)

---

<sup>**[common/lib/bridge.c, line 19 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIUFdljYlKzoZ-pQR9)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.c#L19)):</sup>
Thanks.

---

<sup>**[common/lib/bridge.c, line 42 \[r2\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiLDPV5vy8k8NLHd_FR)** ([raw file](https://github.com/amhk/lokatt/blob/e17f8b1f243b1437b01a64de2ddbcb88423b5961/common/lib/bridge.c#L42)):</sup>
I'm not sure if this is correctly aligned -- is reviewable.io just messing with me? If so, please ignore this comment.

---

<sup>**[common/lib/bridge.c, line 47 \[r2\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiLDabH3ir_L4B7jMHd)** ([raw file](https://github.com/amhk/lokatt/blob/e17f8b1f243b1437b01a64de2ddbcb88423b5961/common/lib/bridge.c#L47)):</sup>
No newline in messages passed to die(), please (a newline is automatically appended).

---

<sup>**[common/lib/bridge.h, line 8 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIOMxwYdsnVZiSBAfI)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.h#L8)):</sup>
Right. I've updated issue #5 with this piece of information.

---

<sup>**[common/liblokatt.py, line 49 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIXyz4oVO0VtVTEOyK)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/liblokatt.py#L49)):</sup>
LogcatSession it is!

---

<sup>**[common/liblokatt.py, line 59 \[r2\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiLE-ktiarzbYgeYve5)** ([raw file](https://github.com/amhk/lokatt/blob/e17f8b1f243b1437b01a64de2ddbcb88423b5961/common/liblokatt.py#L59)):</sup>
Are self.buffer_size and self.session internal, ie should they be prefixed with underscore just like _is_open?

---

**Comment by MartinWallgren** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/3)



---

Do you mind if we postpone this? It will be much easier to implement when we can create lokatt_sessions with files as input. As it is now we would have to mock a lot of the functionality related to lokatt_session and lokatt_channel.

Do you mind if I postpone this for now and create issues for later for:
* add possibility to log session to file, replay session from file
* add test-demux.c
* add test-bridge.c

---

**Comment by amhk** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/3)



---

Sounds reasonable. Will you create the issues listed, please?

---

**Comment by MartinWallgren** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/3)







---

<sup>**[cli/cli.py, line 57 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIVZRPUmj6_SkDZnkO)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/cli/cli.py#L57)):</sup>
I'm now using threading.Event to use in the main thread to wait for the LogcatSession to end.

---

<sup>**[common/lib/bridge.c, line 19 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIUFdljYlKzoZ-pQR9)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.c#L19)):</sup>
Done.

---

<sup>**[common/lib/bridge.c, line 19 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIQLMXMZFFgII0oL62)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/lib/bridge.c#L19)):</sup>
Done.

---

<sup>**[common/lib/bridge.c, line 42 \[r2\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiLDPV5vy8k8NLHd_FR)** ([raw file](https://github.com/amhk/lokatt/blob/e17f8b1f243b1437b01a64de2ddbcb88423b5961/common/lib/bridge.c#L42)):</sup>
Done.

---

<sup>**[common/lib/bridge.c, line 47 \[r2\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiLDabH3ir_L4B7jMHd)** ([raw file](https://github.com/amhk/lokatt/blob/e17f8b1f243b1437b01a64de2ddbcb88423b5961/common/lib/bridge.c#L47)):</sup>
Done.

---

<sup>**[common/liblokatt.py, line 49 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIXyz4oVO0VtVTEOyK)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/liblokatt.py#L49)):</sup>
Done.

---

<sup>**[common/liblokatt.py, line 59 \[r2\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiLE-ktiarzbYgeYve5)** ([raw file](https://github.com/amhk/lokatt/blob/e17f8b1f243b1437b01a64de2ddbcb88423b5961/common/liblokatt.py#L59)):</sup>
Done.

---

<sup>**[common/liblokatt.py, line 60 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIXF40w8ZBxMRIdLDB)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/common/liblokatt.py#L60)):</sup>
Done.

---

**Comment by MartinWallgren** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/3)



---

I'm adding the issues now.

---

**Comment by MartinWallgren** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/3)



---

#6 Log LogcatSession to file
#7 add test cases for demux.c
#8 add test cases for bridge.c

---

**Comment by amhk** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/amhk/lokatt/3)

Reviewed files:
- cli/cli.py @ r3
- common/lib/bridge.c @ r3
- common/liblokatt.py @ r3
- lokatt.py @ r3





---

<sup>**[cli/cli.py, line 57 \[r1\]](https://reviewable.io:443/reviews/amhk/lokatt/3#-JiIVZRPUmj6_SkDZnkO)** ([raw file](https://github.com/amhk/lokatt/blob/7a2611ccfee7a02783220a4c4f3fde97c85f09c4/cli/cli.py#L57)):</sup>
Nice, thanks!

---

**Comment by amhk** [comment]
This pull request has been merged manually.

**Pull request closed without merging**
